Repository SV-Winter-BootCamp-TeamD/backend, pull requests merged in 2024-01, with the labels that each got.

#2 feat: 회원가입 API 구현
  backend/settings.py
  backend/urls.py
  user/__init__.py
  user/apps.py
  user/models.py
  user/serializers.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: 🎀 Feature

#6 feat: 캔버스 생성 API 구현
  backend/settings.py
  backend/urls.py
  canvas/__init__.py
  canvas/apps.py
  canvas/models.py
  canvas/serializers.py
  canvas/tests.py
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#8 feat: 캔버스 이름 수정 API 구현
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#10 feat: 캔버스 삭제 API 구현
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#12 feat: 친구 초대 API 구현
  canvas/models.py
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#14 feat: AWS S3 버킷 직접 배경 업로드 API 구현
  backend/settings.py
  canvas/urls.py
  component/__init__.py
  component/apps.py
  component/models.py
  component/s3_utils.py
  component/tests.py
  component/views.py
  requirements.txt
Labels: 🎀 Feature

#17 feat: AI 배경 생성 및 AWS S3 버킷 업로드 API 구현
  backend/settings.py
  canvas/urls.py
  component/AI_utils.py
  component/apps.py
  component/views.py
  requirements.txt
Labels: 🎀 Feature

#19 feat: AI 스티커 생성 및 AWS S3 버킷 업로드 API 구현
  Dockerfile
  canvas/urls.py
  component/nukki.py
  component/views.py
  requirements.txt
Labels: 🎀 Feature

#20 feat: 직접 텍스트 업로드 API 구현
  canvas/urls.py
  component/models.py
  component/serializers.py
  component/views.py
Labels: 🎀 Feature

#23 feat: 선택한 AI 배경 업로드 API 구현
  canvas/urls.py
  component/views.py
Labels: 🎀 Feature

#25 feat: 선택한 AI 스티커 업로드 API 구현
  canvas/urls.py
  component/views.py
Labels: 🎀 Feature

#26 feat: 요소 삭제 API 구현
  canvas/urls.py
  component/views.py
Labels: 🎀 Feature

#28 feat: 직접 업로드한 배경 조회 API 구현
  component/serializers.py
  component/views.py
Labels: 🎀 Feature

#31 feat: AI 생성한 스티커 조회 API 구현
  canvas/migrations/0001_initial.py
  canvas/migrations/__init__.py
  component/migrations/0001_initial.py
  component/migrations/__init__.py
  component/serializers.py
  component/views.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: 🎀 Feature

#33 feat: 캔버스 저장 API 구현
  canvas/migrations/0001_initial.py
  canvas/migrations/__init__.py
  canvas/urls.py
  canvas/views.py
  component/migrations/0001_initial.py
  component/migrations/__init__.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: 🎀 Feature

#35 feat: 배경 추천 API 구현
  backend/settings.py
  canvas/urls.py
  component/recommend.py
  component/views.py
Labels: 🎀 Feature

#37 feat: 개인 캔버스 전체 조회 API 구현
  canvas/migrations/0001_initial.py
  canvas/migrations/__init__.py
  canvas/serializers.py
  canvas/urls.py
  canvas/views.py
  component/migrations/0001_initial.py
  component/migrations/__init__.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: 🎀 Feature

#40 fix: 친구 초대 API 수정
  canvas/urls.py
  canvas/views.py
Labels: 🛠️ BugFix

#41 feat: 공유 캔버스 전체 조회 API 구현
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#43 feat: 웹 소켓 연결
  Dockerfile
  backend/asgi.py
  backend/settings.py
  canvas/consumers.py
  canvas/migrations/0001_initial.py
  canvas/migrations/__init__.py
  canvas/routing.py
  canvas/urls.py
  canvas/views.py
  component/migrations/0001_initial.py
  component/migrations/__init__.py
  docker-compose.yml
  requirements.txt
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: 🎀 Feature

#44 feat: 캔버스 상세 조회 API 구현
  canvas/serializers.py
  canvas/urls.py
  canvas/views.py
Labels: 🎀 Feature

#46 fix: 개인 캔버스 전체 조회 API 수정
  canvas/serializers.py
  canvas/views.py
Labels: 🛠️ BugFix

#49 fix: 캔버스 저장 API 수정
  canvas/views.py
  component/models.py
Labels: 🛠️ BugFix

#51 fix: 캔버스 상세 조회 API 수정
  canvas/views.py
Labels: 🛠️ BugFix

#55 feat: 초대 목록 조회 API 구현 및 로직 변경
  canvas/urls.py
  canvas/views.py
  component/views.py
Labels: 🛠️ BugFix, 🎀 Feature

#56 feat: 웹 소켓 resize 추가
  canvas/consumers.py
Labels: 🛠️ BugFix

#57 feat: Celery&RabbitMQ 비동기 처리 구현
  backend/__init__.py
  backend/celery.py
  backend/settings.py
  component/tasks.py
  component/views.py
  docker-compose.yml
  requirements.txt
Labels: 🎀 Feature

#59 fix: 캔버스 상세 조회 API 수정
  canvas/views.py
Labels: 🛠️ BugFix

#61 fix: 배경 업로드 및 캔버스 상세 조회 로직 수정
  canvas/views.py
  component/views.py
Labels: 🛠️ BugFix

#64 fix: 배경 제거 기능 수정
  component/nukki.py
  requirements.txt
Labels: 🛠️ BugFix

#66 feat: 선택한 추천 배경 업로드 API 구현
  component/models.py
  component/views.py
Labels: 🎀 Feature

#70 feat: AI 생성한 배경 조회 API 구현
  component/views.py
Labels: 🎀 Feature

#73 fix: canvas models 수정
  canvas/models.py
Labels: 🛠️ BugFix

#75 fix: 캔버스 저장 API 수정
  canvas/models.py
  canvas/views.py
Labels: 🛠️ BugFix

#77 fix: 캔버스 저장 API S3 URL 형식 수정
  canvas/views.py
Labels: 🛠️ BugFix

#81 fix: 캔버스 생성 API 수정
  canvas/consumers.py
  canvas/views.py
Labels: 🛠️ BugFix

#83 fix: 캔버스 생성 API 수정
  canvas/consumers.py
  canvas/views.py
Labels: 🛠️ BugFix

#85 feat: 웹소켓 기능 추가
  canvas/consumers.py
  component/models.py
Labels: 🎀 Feature

#87 fix: 웹 소켓 기능 수정
  canvas/consumers.py
Labels: 🛠️ BugFix

#89 fix: 캔버스 저장 API 수정
  canvas/views.py
Labels: 🛠️ BugFix

#91 fix: 웹 소켓 기능 수정
  canvas/consumers.py
Labels: 🛠️ BugFix

#93 feat: Prometheus, Grafana, Node Exporter 모니터링 구현
  backend/settings.py
  backend/urls.py
  docker-compose.yml
  prometheus/prometheus.yml
  requirements.txt
Labels: 🎀 Feature

#95 feat: 웹 소켓 기능 추가
  canvas/consumers.py
Labels: 🎀 Feature

#97 feat: 웹 소켓 기능 추가
  canvas/consumers.py
Labels: 🎀 Feature

#99 fix: 캔버스 상세 조회 API 수정
  canvas/views.py
Labels: 🛠️ BugFix

#101 Swaager 추가 구현
  component/views.py
Labels: 📝 Docs

#104 feat: CAdvisor 추가 구현
  docker-compose.yml
  prometheus/prometheus.yml
Labels: 🎀 Feature

#106 feat: AlertManager 구현
  .gitignore
  docker-compose.yml
  prometheus/alert.yml
  prometheus/prometheus.yml
Labels: 🎀 Feature

#109 feat: Gunicorn 연동
  requirements.txt
Labels: 🎀 Feature

#111 fix: Gunicorn 연동을 위한 Dockerfile 수정
  Dockerfile
Labels: 🛠️ BugFix

#113 fix: CORS 오류 해결
  backend/settings.py
Labels: 🛠️ BugFix

#115 fix: RDS 연동을 위한 requirements.txt 수정
  requirements.txt
Labels: 🛠️ BugFix

#117 fix: RDS 연동을 위한 라이브러리 추가 및 setting 수정
  backend/settings.py
  requirements.txt
Labels: 🛠️ BugFix

#120 fix: settings.py 도메인 허용
  backend/settings.py
Labels: 🛠️ BugFix

#122 fix: settings.py 도메인 허용 수정
  backend/settings.py
Labels: 🛠️ BugFix

#124 fix: 웹소켓 기능 수정
  canvas/consumers.py
  component/models.py
Labels: 🛠️ BugFix

#126 fix: 웹 소켓 기능 수정
  canvas/consumers.py
  component/models.py
Labels: 🛠️ BugFix
